### ISSUE TITLE
why do you use Redis Pubsub 

### ISSUE THREAD

**Issue by MaryLilian** [GiorgiKhunashvili/spilo#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by GiorgiKhunashvili** [comment]
Hello, this is good question. I had good reasons why i chose redis over kafka or rabbitmq. Kafka and RabbitMQ store published events on disk to ensure that if listener(subscribed) server goes down and misses some published events those servers will be able to receive missed messages after they will be alive again this is one big difference between redis and Kafka, RabbitMQ. redis does not store events on disk if you want short living messages than you should go with redis.
In my case i wanted to distribute messages across servers and did not care about if some clinets will miss some messages if they will disconnect.

If you want some complex routings and persistent messages you should go with rabbitmq.
If you want shored lived messages(events) you should go with redis.
While if your application has large amounts of data, then Kafka would be a better option.

Also there is one concept how you receive events for example: when you publish event to broker rabbitmq will send this event to all subscribed servers but in kafka things are little bit different kafka uses concept called long pulling for instance clients will make request in every 10 millisecond to kafka to retrieve any new events.

If you have any other questions let me know.
